<<<<<<< HEAD
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
print('helloworlds')
=======
print('helloworld')
print('test')
print('testing')
print('broken')
>>>>>>> 2a921973d0ae26deb58453378b00cd531c7e1b15
